---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: alex-gke-ingress-test-ingress
  namespace: alex-gke-ingress-test
  annotations:
    ingress.gcp.kubernetes.io/pre-shared-cert: alex-gke-one
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
    - host: alex-gke-one.clio.dev
      http:
        paths:
          - path: /*
            pathType: Prefix
            backend:
              serviceName: alex-gke-ingress-test-service
              servicePort: 80